export default {
  "container": "_container_1tuln_1",
  "box": "_box_1tuln_4",
  "flex": "_flex_1tuln_60",
  "songItem": "_songItem_1tuln_68",
  "title": "_title_1tuln_72",
  "autoplay-container": "_autoplay-container_1tuln_83",
  "autoplay-label": "_autoplay-label_1tuln_90",
  "toggle_input": "_toggle_input_1tuln_95",
  "toggle_label": "_toggle_label_1tuln_102",
  "isearch-container": "_isearch-container_1tuln_135",
  "isearch-label": "_isearch-label_1tuln_139",
  "close-btn": "_close-btn_1tuln_143",
  "overlay": "_overlay_1tuln_152",
  "overlay-iframe": "_overlay-iframe_1tuln_165",
  "overlay-inner": "_overlay-inner_1tuln_170",
  "scroll": "_scroll_1tuln_176",
  "link": "_link_1tuln_228",
  "fadein": "_fadein_1tuln_1",
};
