export default {
  "container": "_container_9wuct_1",
  "box": "_box_9wuct_9",
  "songItem": "_songItem_9wuct_16",
  "title": "_title_9wuct_20",
  "autoplay-container": "_autoplay-container_9wuct_25",
  "autoplay-label": "_autoplay-label_9wuct_32",
  "toggle_input": "_toggle_input_9wuct_37",
  "toggle_label": "_toggle_label_9wuct_44",
  "isearch-container": "_isearch-container_9wuct_77",
  "isearch-label": "_isearch-label_9wuct_81",
  "scroll": "_scroll_9wuct_85",
  "fadein": "_fadein_9wuct_1",
  "link": "_link_9wuct_104",
};
